apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic-5nkr
  namespace: syahmed-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:c0446eea5cc60e5ee951f166c565d3a8427722497657c1516b56f97128160e87
        name: my-go
        resources: {}
status: {}
